var indexData = {
  itemWidth : (screen.width - 15) / 2.0 ,
  adimages : [
        {
            "title": "",
            "img_url": "http://image.xianrou.com/upload/carouselpic/v/4213dqa0j8vg.jpg",
            "content": "",
            "type": 2,
            "user_id": "44363"
        },
        {
            "title": "",
            "img_url": "http://image.xianrou.com/upload/carouselpic/8/42be6ba4sl84.jpg",
            "content": "",
            "type": 2,
            "user_id": "30231"
        },
        {
            "title": "",
            "img_url": "http://image.xianrou.com/upload/carouselpic/1/42dsb5p0r414.jpg",
            "content": "",
            "type": 2,
            "user_id": "19018"
        }
  ],
  result : [
        {
            "user_id": 1301,
            "nickname": "松果儿",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/8/14699301855890.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 1301,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/8/14699301855890.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/g/14670025874737.jpg_100.jpg",
            "huanxin_uid": "4028d572118s",
            "old_avatar": "",
            "role_type": 0,
            "sort": 0,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/8/41jqqqsr241g.jpg_540.jpg"
        },
        {
            "user_id": 2051,
            "nickname": "黑暗摄影师Luke",
            "role_id": 9,
            "city_id": 0,
            "city_name": "上海",
            "identified": 1,
            "identify_title": "鲜肉认证：知名摄影师",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14677280218150.jpeg_xr200.jpg",
            "gender": 1,
            "location_id": 2051,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14677280218150.jpeg",
            "stars": 3,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/j/14595992848753.jpeg_100.jpg",
            "huanxin_uid": "40vba2hhk0ug",
            "old_avatar": "",
            "role_type": 0,
            "sort": 0,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/u/41livielcvg8.jpg_540.jpg"
        },
        {
            "user_id": 35998,
            "nickname": "娜露selena",
            "role_id": 9,
            "city_id": 0,
            "city_name": "上海",
            "identified": 1,
            "identify_title": "鲜肉认证：模特、网红",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/v/14621692815009.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 35998,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/v/14621692815009.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/j/14595992848753.jpeg_100.jpg",
            "huanxin_uid": "41q2eet92bvs",
            "old_avatar": "",
            "role_type": 0,
            "sort": 0,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/v/41rhqa6mtt3c.jpg_540.jpg"
        },
        {
            "user_id": 36115,
            "nickname": "吹泡泡",
            "role_id": 9,
            "city_id": 0,
            "city_name": "重庆",
            "identified": 1,
            "identify_title": "认证：新锐摄影师、推女郎合作摄影师",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/a/14661005326201.jpeg_xr200.jpg",
            "gender": 1,
            "location_id": 36115,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/a/14661005326201.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/t/14594519373029.jpg_100.jpg",
            "huanxin_uid": "41q3vf3j11ao",
            "old_avatar": "",
            "role_type": 0,
            "sort": 0,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/a/4252ce06qrds.jpg_540.jpg"
        },
        {
            "user_id": 70048,
            "nickname": "Flower朱可儿",
            "role_id": 9,
            "city_id": 0,
            "city_name": "上海",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/c/14667002769266.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 70048,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/c/14667002769266.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/c/14639046201301.jpg_100.jpg",
            "huanxin_uid": "4273aj6jpjcg",
            "old_avatar": "",
            "role_type": 0,
            "sort": 0,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/c/4277tru6c5to.jpg_540.jpg"
        },
        {
            "user_id": 75567,
            "nickname": "Sugar小甜心心",
            "role_id": 9,
            "city_id": 0,
            "city_name": "宜昌",
            "identified": 1,
            "identify_title": "鲜肉认证：模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/7/14673802125845.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 75567,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/7/14673802125845.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/l/14684666726037.jpeg_100.jpg",
            "huanxin_uid": "429ds8j9fs70",
            "old_avatar": "",
            "role_type": 0,
            "sort": 0,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/7/42a73o8vtejk.jpg_540.jpg"
        },
        {
            "user_id": 85438,
            "nickname": "北娃大王",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：大妞范创始人 知名摄影师",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/4/14681393634691.jpeg_xr200.jpg",
            "gender": 1,
            "location_id": 85438,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/4/14681393634691.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/s/14674235058866.jpeg_100.jpg",
            "huanxin_uid": "42cmfpi0ua4k",
            "old_avatar": "",
            "role_type": 0,
            "sort": 0,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/4/42cmidnq24h0.jpg_540.jpg"
        },
        {
            "user_id": 85576,
            "nickname": "王涛",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：新锐时尚摄影师",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/h/14681555036185.jpeg_xr200.jpg",
            "gender": 1,
            "location_id": 85576,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/h/14681555036185.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/g/14687314984309.jpeg_100.jpg",
            "huanxin_uid": "42cnup5h19hs",
            "old_avatar": "",
            "role_type": 0,
            "sort": 0,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/h/42cobb89tp1g.jpg_540.jpg"
        }
    ],
    invite: {
        "title": "邀请好友",
        "img_url": "https://api.xianroukeji.com/upload/invitepic/s/4205roo4dqsc.jpg",
        "content": "赚取网红和壕的分成",
        "subcontent": "他(她)的每笔消费或收入，你都分成10%",
        "type": 4
    },
    recommends: [
        {
            "user_id": 6696,
            "nickname": "哈尼宝宝",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：车模",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/7/14537071584556.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 6696,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/7/14537071584556.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/q/14649674732882.jpeg_100.jpg",
            "huanxin_uid": "413lq2vpk47o",
            "old_avatar": "",
            "role_type": 0,
            "sort": 100013,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/7/41psd69qnh0c.jpg_540.jpg"
        },
        {
            "user_id": 37568,
            "nickname": "陈友熙😇",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：演员、网红",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/v/14617790741589.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 37568,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/v/14617790741589.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14694415398714.jpg_100.jpg",
            "huanxin_uid": "41qji0ir5qvk",
            "old_avatar": "",
            "role_type": 0,
            "sort": 100013,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/v/41qjlldt0egs.jpg_540.jpg"
        },
        {
            "user_id": 110746,
            "nickname": "赵小米，Kitty",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/h/14676860228136.jpg_xr200.jpg",
            "gender": 2,
            "location_id": 110746,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/h/14676860228136.jpg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14694415398714.jpg_100.jpg",
            "huanxin_uid": "d147pp76bhs",
            "old_avatar": "",
            "role_type": 0,
            "sort": 100013,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/h/42bdv77m13a8.jpg_540.jpg"
        },
        {
            "user_id": 104719,
            "nickname": "陈美琳Mandy",
            "role_id": 9,
            "city_id": 0,
            "city_name": "深圳",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/e/14581056023345.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 104719,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/e/14581056023345.jpeg",
            "stars": 2,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/7/14467356219151.jpeg_100.jpg",
            "huanxin_uid": "cudc0oiseeo",
            "old_avatar": "",
            "role_type": 0,
            "sort": 100013,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/e/41m3tkegh9rk.jpg_540.jpg"
        },
        {
            "user_id": 63845,
            "nickname": "lavinia",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：模特、造型师",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14654521577182.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 63845,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14654521577182.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14694415398714.jpg_100.jpg",
            "huanxin_uid": "42522t0sv1ug",
            "old_avatar": "",
            "role_type": 0,
            "sort": 100012,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/u/42iu14765hms.jpg_540.jpg"
        },
        {
            "user_id": 100083,
            "nickname": "Mali",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：车模",
            "avatar": "http://imagetest.xianroukeji.com/2016/08/16/57b2286367611_b.jpg",
            "gender": 2,
            "location_id": 100083,
            "big_avatar": "http://imagetest.xianroukeji.com/2016/08/16/57b228639d186_f.jpg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/2/14617656500855.jpeg_100.jpg",
            "huanxin_uid": "42it5ajlu8c0",
            "old_avatar": "",
            "role_type": 0,
            "sort": 100012,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/avatar/c/14703238251048.jpeg_690.jpg"
        },
        {
            "user_id": 36180,
            "nickname": "可乐Vicky-",
            "role_id": 9,
            "city_id": 0,
            "city_name": "重庆",
            "identified": 1,
            "identify_title": "鲜肉认证：模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/m/14694671717294.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 36180,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/m/14694671717294.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14704205119114.jpeg_100.jpg",
            "huanxin_uid": "41q6smoei9m8",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10099,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/m/42ges5b567hs.jpg_540.jpg"
        },
        {
            "user_id": 74650,
            "nickname": "玛鲁娜manuela",
            "role_id": 9,
            "city_id": 0,
            "city_name": "深圳",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/1/14670526457429.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 74650,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/1/14670526457429.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/l/14595631878252.jpeg_100.jpg",
            "huanxin_uid": "4293huhoua18",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10099,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/1/42j25laj5q7o.jpg_540.jpg"
        },
        {
            "user_id": 31352,
            "nickname": "贵彬",
            "role_id": 9,
            "city_id": 0,
            "city_name": "上海",
            "identified": 1,
            "identify_title": "鲜肉认证：知名摄影师",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/8/14605138421606.jpeg_xr200.jpg",
            "gender": 1,
            "location_id": 31352,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/8/14605138421606.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/v/14554944195859.jpg_100.jpg",
            "huanxin_uid": "41n0t6cb7s8s",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10098,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/8/41n12hp0hqo0.jpg_540.jpg"
        },
        {
            "user_id": 100215,
            "nickname": "雅熙CiCi酱丶",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/d/14703660332376.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 100215,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/d/14703660332376.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/7/14537071584556.jpeg_100.jpg",
            "huanxin_uid": "42j0vtbfpjd4",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10098,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/d/42j1rci6ouro.jpg_540.jpg"
        },
        {
            "user_id": 37434,
            "nickname": "Amanda无敌美辣妈",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：视频红人",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/k/14617644042386.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 37434,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/k/14617644042386.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/g/14627594349927.jpeg_100.jpg",
            "huanxin_uid": "41qim1kh1vk0",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10098,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/k/cvg3jasmjn8.jpg_540.jpg"
        },
        {
            "user_id": 92994,
            "nickname": "鱼包鱼包",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：摄影师",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/j/14689054673910.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 92994,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/j/14689054673910.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/r/14532751677280.jpeg_100.jpg",
            "huanxin_uid": "42es59r4moj0",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10098,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/j/42esbod633ms.jpg_540.jpg"
        },
        {
            "user_id": 29930,
            "nickname": "Ada黛欣霓",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：演员、网红",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/e/14603083383571.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 29930,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/e/14603083383571.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/o/14664746931603.jpeg_100.jpg",
            "huanxin_uid": "41me8943hde4",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10098,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/e/41q3k8938j5g.jpg_540.jpg"
        },
        {
            "user_id": 56204,
            "nickname": "米妮Mini宝宝",
            "role_id": 9,
            "city_id": 0,
            "city_name": "上海",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/o/14686795937922.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 56204,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/o/14686795937922.jpeg",
            "stars": 1,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/n/14695129851392.jpg_100.jpg",
            "huanxin_uid": "421rpmu01bo8",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10098,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/o/42etbrgjooho.jpg_540.jpg"
        },
        {
            "user_id": 47928,
            "nickname": "刘娅希",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：模特、艺人",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/9/14628726958785.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 47928,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/9/14628726958785.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/m/14642889701354.jpeg_100.jpg",
            "huanxin_uid": "41tnfofl8l9k",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10097,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/9/19if81qd160.jpg_540.jpg"
        },
        {
            "user_id": 102877,
            "nickname": "赵惟依",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/o/14412076621139.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 102877,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/o/14412076621139.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/c/14423890684547.jpeg_100.jpg",
            "huanxin_uid": "cpjm8cp76o8",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10097,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover//4005ii29b8ck.jpg_540.jpg"
        },
        {
            "user_id": 48297,
            "nickname": "林萌萌cc",
            "role_id": 9,
            "city_id": 0,
            "city_name": "成都",
            "identified": 1,
            "identify_title": "认证：美女鲜肉",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14629404483165.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 48297,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/u/14629404483165.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/q/14680294384608.jpeg_100.jpg",
            "huanxin_uid": "41ttkmp0hvuo",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10096,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/u/42chbmhsul9o.jpg_540.jpg"
        },
        {
            "user_id": 2043,
            "nickname": "苏可可",
            "role_id": 9,
            "city_id": 0,
            "city_name": "北京",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/2/14521825138006.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 131141,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/2/14521825138006.jpeg",
            "stars": 2,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/m/14593959550301.jpg_100.jpg",
            "huanxin_uid": "40vb4am8co2k",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10096,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/2/csnv7vbcqss.jpg_540.jpg"
        },
        {
            "user_id": 33675,
            "nickname": "顾欣怡Baby",
            "role_id": 9,
            "city_id": 0,
            "city_name": "重庆",
            "identified": 1,
            "identify_title": "鲜肉认证：模特、网红",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/o/14619567607984.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 33675,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/o/14619567607984.jpeg",
            "stars": 0,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/j/14596392784502.jpeg_100.jpg",
            "huanxin_uid": "41ocbirlbfo8",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10096,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/o/41ph1th1mgas.jpg_540.jpg"
        },
        {
            "user_id": 58370,
            "nickname": "佘贝拉Bella",
            "role_id": 9,
            "city_id": 0,
            "city_name": "成都",
            "identified": 1,
            "identify_title": "鲜肉认证：明星模特",
            "avatar": "http://imagetest.xianroukeji.com/upload/avatar/i/14647855562030.jpeg_xr200.jpg",
            "gender": 2,
            "location_id": 58370,
            "big_avatar": "http://imagetest.xianroukeji.com/upload/avatar/i/14647855562030.jpeg",
            "stars": 2,
            "daemon": 1,
            "daemon_avatar": "http://imagetest.xianroukeji.com/upload/avatar/j/14596392784502.jpeg_100.jpg",
            "huanxin_uid": "4235afeuf1ig",
            "old_avatar": "",
            "role_type": 0,
            "sort": 10096,
            "photo": 1,
            "cover": "http://imagetest.xianroukeji.com/upload/cover/i/423e1c40pels.jpg_540.jpg"
        }
    ]
}

Page({
  data:indexData,
  onLoad:function(options){
    
  },
  onReady:function(){
    // 页面渲染完成
  },
  onShow:function(){
    // 页面显示
  },
  onHide:function(){
    // 页面隐藏
  },
  onUnload:function(){
    // 页面关闭
  }
})